### ISSUE TITLE
Now needs an API key

### ISSUE THREAD

**Issue by tuukka** [citybikes/citybikes.github.io#12]
The data is not loading because an API key is now required. More info: https://digitransit.fi/en/developers/api-registration/ 😥

**Comment by hugovk** [comment]
Yeah, I noticed after the Fillarit app on Android was missing bikes (now fixed), and then checked here as a fallback...

I've signed up for a key and added it here, and https://citybikes.github.io is (except for the map) back in action! Thanks!

**Comment by hugovk** [comment]
And map fixed in https://github.com/citybikes/citybikes.github.io/pull/14.

**Comment by tuukka** [comment]
Thank you - perfect!
